replicaCount: 2

image:
  repository: 430118842689.dkr.ecr.ap-south-1.amazonaws.com/smyik
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  create: true

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

# PostgreSQL Configuration using CloudNativePG
postgresql:
  enabled: true
  cluster:
    name: smyik-db
    instances: 1
    
    postgresql:
      parameters:
        max_connections: "200"
        shared_buffers: "128MB"
        
    bootstrap:
      initdb:
        database: simple_bank
        owner: root
        secret:
          name: banking-db-root-credentials
          
    storage:
      size: 2Gi
      storageClass: "local-path"

# Database credentials
database:
  username: root
  password: secret
  database: simple_bank

# Application environment variables
app:
  env:
    DB_DRIVER: postgres
    SERVER_ADDRESS: "0.0.0.0:8080"
    ACCESS_TOKEN_DURATION: "15m"
    TOKEN_SYMMETRIC_KEY: "3ae505269c823e6aaf5825f16e203781"
