prometheus:
  prometheusSpec:
    # Retention period for metrics
    retention: 4d
    retentionSize: "2GB"
    
    # Resource limits (adjust based on your cluster size)
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
    
    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi
    
    # Enable service monitors for auto-discovery
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

# Node exporter - collects node metrics
prometheus-node-exporter:
  enabled: true

# Kube-state-metrics - collects k8s object metrics
kube-state-metrics:
  enabled: true
